### PR TITLE
Update for Django 1.10 among other things

### PR DESCRIPTION
**Pull request by matthiask**
Hey

Thanks for this project!

Just wanted to let you know that I'm working on django-cte-trees a bit. Until now I didn't make too invasive changes, but that might change depending on whether you're still interested in maintaining this project and your feedback here. If my experiment with django-cte-trees works well I would be willing to maintain this project, but if I don't have to do more free work then that's alright with me :-)  (All of this is meant in the friendliest way possible, I hope it comes across as such.)

I added a .travis.yml file so that Travis CI runs tests automatically: https://travis-ci.org/matthiask/django-cte-trees

I'd like to change the code base to be flake8-clean and run flake8 as well on CI (as I do with most of my open source projects)

While I hate `getattr` I'm still thinking that maybe we should use `_cte_node_(ordering|depth|path)` instead of hard-coding `ordering`, `depth` and `path` as fields. (Maybe not, maybe I should just rename the `path` field on my `Page` model instead.)

I have been thinking a bit about the performance implications of always running the CTE and have been wondering whether it is possible to build a simple API which allows to add the CTE only when it's wanted (`CTEQuerySet.treeify()` or something — not a good name, but yeah.)

Any feedback?

### CODE REVIEW

**Comment by matthiask** [comment]
By the way, the version changes weren't made by me. I built on top of https://github.com/stjosephcontent/django-cte-trees and the first few commits came from there.

**Comment by matthiask** [comment]
Since I'm a bit under pressure (time-wise) I forked the project as https://github.com/matthiask/django-cte-forest. I'm still interested in merging and continuing this discussion but had to move forward to get a project online quickly.

Thanks!

**Comment by matthiask** [comment]
Hi @petrounias 

Are you still interested resp. do you still have the time to maintain django-cte-tree? If not I'd be happy to take over. (pypi, readthedocs, github)

Thanks again for the project, it's awesome and very useful to us.

**Comment by petrounias** [comment]
Hi @matthiask, unfortunately I do not use this project at work right now and I do not have sufficient time to maintain it. Happy to merge all changes and glad it's useful to you.

**Comment by matthiask** [comment]
Thank you! I don't expect many changes, but happy to help out.

(If you're interested to take a look, [feincms3](https://github.com/matthiask/feincms3) is my main use for cte-trees right now)

**Pull request merged**
